# NUMPY Basics

In [2]:
import numpy as np

a=np.array([1,2,3,4,5]) #1-D
a

array([1, 2, 3, 4, 5])

In [3]:
b=np.array([[1,2,3],[1,2,3]]) #2-D
b

array([[1, 2, 3],
       [1, 2, 3]])

In [44]:
c=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])  #3-D
c

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [7]:
q=np.ones((3,3),dtype=int)
q

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [9]:
w=np.eye(3,3,dtype=float)
w

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
a.shape

(5,)

In [11]:
w.shape   #shape method

(3, 3)

In [43]:
A=np.array([1,2,3,4,5,6,7,8])  # slicing in ndarray
print(A[:5])
print(A[1:])
print(A[:])
print(A[::-1])
print(A[::-2])
print(A[-8:-1])


[1 2 3 4 5]
[2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
[8 7 6 5 4 3 2 1]
[8 6 4 2]
[1 2 3 4 5 6 7]


In [28]:
e=np.array([[1,2,3],[4,5,6]])  #for indexing
            #  0       1
print(e)
print(e[:,:2])

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]


In [39]:
e=np.array([[1,2,3],[4,5,6]])  
print(e[1,2])
print(e[0,1])

6
2


In [42]:
a=np.arange(1,21).reshape(5,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [46]:
dir(a) # a is a numpy array

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [55]:
np.zeros(3)  # zeros method

array([0., 0., 0.])

In [61]:
a1=np.empty(2)  # empty method
a1

array([7.36754195e+005, 7.98467880e+146])

In [60]:
a2=np.linspace(0,10,num=5)  #linspace to divide the a
a2

array([ 0.  ,  2.75,  5.5 ,  8.25, 11.  ])

In [66]:
a3=[1,2,3]   # list
a4=np.asarray(a3)  #asarray method
print(a4)
print(type(a3))    #type is list
print(type(a4))   #type is ndarray

[1 2 3]
<class 'list'>
<class 'numpy.ndarray'>


In [68]:
np.logspace(0,10,2)

array([1.e+00, 1.e+10])

In [69]:
a4.size             #size returns no.of elements

3

In [71]:
x=np.array([[1,2,3],[2,3,4]]).size
x

6

In [73]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [74]:
a.size

20

In [75]:
a.shape

(5, 4)

In [79]:
a8=a.reshape(4,5) 
#reshape will reshapes the array into any shape based on dimension
a8

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [80]:
a8.shape

(4, 5)

In [92]:
z=np.array([1,2,3,4,5])   #mean
print("the MEAN of ",z,"is :",z.mean())

the MEAN of  [1 2 3 4 5] is : 3.0


In [91]:
z1=np.array([1,2,3,4,5])  #standard deviation
print("the STD of ",z1,"is :",z1.std())

the STD of  [1 2 3 4 5] is : 1.4142135623730951


In [97]:
z2=np.array([1,2,3,4,5])  #varience
print("the varience of ",z2,"is :",z2.var())

the varience of  [1 2 3 4 5] is : 2.0


In [89]:
y=np.array([[[1,2],[3,4]],[[1,2],[1,2]]])   
print(y)
y.shape            #shape method for 3-D

[[[1 2]
  [3 4]]

 [[1 2]
  [1 2]]]


(2, 2, 2)

In [96]:
np.full((2,2),20.1)  #full method

array([[20.1, 20.1],
       [20.1, 20.1]])

In [116]:
a12=np.array([1,3,5,7,2,4,6,10])
a12.sort()      
#sort() method
print(a12)
a13=np.array([[4,1,2],[4,5,2]])  
np.sort(a13,axis=1)  

[ 1  2  3  4  5  6  7 10]


array([[1, 2, 4],
       [2, 4, 5]])

In [108]:
y=np.array([[1,2],[3,4]]) 
y

array([[1, 2],
       [3, 4]])

In [103]:
z4=np.array([[10,20],[30,40]])
z4

array([[10, 20],
       [30, 40]])

concat=np.concatenate((y,z4),axis=0)#concatenate method axis=0 rows 
concat

In [114]:
concat=np.concatenate((y,z4),axis=1)#concatenate method axis=1 cols 
concat

array([[ 1,  2, 10, 20],
       [ 3,  4, 30, 40]])

In [132]:
a12=np.array([2,0,1,5,4,1,9])  #argsort method returns array of indices from sorted array compared with original array
a11=np.argsort(a12)
print("Output sorted array indices",a11)
print()
print("Output sorted array :",a12[a11])

Output sorted array indices [1 2 5 0 4 3 6]

Output sorted array : [0 1 1 2 4 5 9]


In [142]:
aq=np.array([[1,2,3],[1,2,3]]).ndim  #ndim
aq

2

In [ ]:
aq=np.array([[1,2,3],[1,2,3]])
print(aq[aq<3])        #different case in accessing

In [145]:
p=np.array([1,3,6,9,23,12,43,30])
print(p[p%3==0])   #different case in accessing

[ 3  6  9 12 30]
